//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Qunatity { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Status { get; set; }
        public int DonorId { get; set; }
    
        public virtual Donor Donor { get; set; }
    }
}
